### ISSUE TITLE
Check docker_compose_version to latest from internet if not provided

### ISSUE THREAD

**Issue by bkmeneguello** [Bessonov/ansible-role-docker-compose#1]
This should be the default behavior, instead of an old fixed version

**Comment by Bessonov** [comment]
Hey, @bkmeneguello, thank you for your input! You're right, that outdated and fixed version isn't optimal. But general, I like a controlled versions. What do you think about requirement to set version instead of provide a version? Or my be like `docker_compose_version: latest`?

**Comment by bkmeneguello** [comment]
It's perfect

**Comment by Bessonov** [comment]
Nice! Can you create a pull request?

**Comment by Bessonov** [comment]
@bkmeneguello Thank you for your contribution to open source! New version is released now. :+1:
